name: Main
on: 
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'BeatTogether.LiteNetLib/**'
      - 'BeatTogether.LiteNetLib.sln'
      - '.github/workflows/main.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'BeatTogether.LiteNetLib/**'
      - 'BeatTogether.LiteNetLib.sln'
      - '.github/workflows/main.yml'
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
      - name: Build
        id: Build
        run: dotnet build BeatTogether.LiteNetLib -c Release
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
      - name: Test
        id: Test
        run: dotnet test BeatTogether.LiteNetLib.Tests -c Release
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
          source-url: https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Pack
        id: Pack
        run: dotnet pack BeatTogether.LiteNetLib -c Release --output nupkgs -p:IsPack=true
      - name: Publish
        id: Publish
        run: dotnet nuget push nupkgs/*.nupkg -k ${GITHUB_TOKEN} -s "github" --skip-duplicate